version: '3.8'

services:
  # Database Service (Development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: ecommerce-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-dev-network

  # Backend API Service (Development with hot reload)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://dev:dev123@postgres-dev:5432/ecommerce_dev
      SECRET_KEY: dev-secret-key-not-for-production
      ENVIRONMENT: development
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    ports:
      - "8003:8002"
    depends_on:
      postgres-dev:
        condition: service_healthy
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]
    networks:
      - ecommerce-dev-network

  # WhatsApp Bot Service (Development)
  whatsapp-bot-dev:
    build:
      context: ./whatsapp-bot-fastapi
      dockerfile: Dockerfile
    container_name: ecommerce-whatsapp-bot-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://dev:dev123@postgres-dev:5432/ecommerce_dev
      BACKEND_URL: http://backend-dev:8002
      ENVIRONMENT: development
    volumes:
      - ./whatsapp-bot-fastapi:/app
      - bot_dev_data:/app/data
    ports:
      - "9002:9001"
    depends_on:
      - backend-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9001", "--reload"]
    networks:
      - ecommerce-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: ecommerce-redis-dev
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - ecommerce-dev-network

volumes:
  postgres_dev_data:
    driver: local
  backend_dev_data:
    driver: local
  bot_dev_data:
    driver: local

networks:
  ecommerce-dev-network:
    driver: bridge