"""Add multi-tenant auth tables

Revision ID: f1c8a481350d
Revises: 
Create Date: 2025-08-15 21:33:07.266320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c8a481350d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_clients_id'), 'tenant_clients', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_clients_slug'), 'tenant_clients', ['slug'], unique=True)
    op.create_table('tenant_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('total', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['tenant_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_orders_client_code', 'tenant_orders', ['client_id', 'code'], unique=True)
    op.create_index('ix_tenant_orders_client_created', 'tenant_orders', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tenant_orders_client_id'), 'tenant_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_tenant_orders_created_at'), 'tenant_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_orders_id'), 'tenant_orders', ['id'], unique=False)
    op.create_table('tenant_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['tenant_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_users_client_email', 'tenant_users', ['client_id', 'email'], unique=True)
    op.create_index(op.f('ix_tenant_users_client_id'), 'tenant_users', ['client_id'], unique=False)
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_users_id'), 'tenant_users', ['id'], unique=False)
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.drop_index(op.f('ix_tenant_users_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_client_id'), table_name='tenant_users')
    op.drop_index('ix_tenant_users_client_email', table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_tenant_orders_id'), table_name='tenant_orders')
    op.drop_index(op.f('ix_tenant_orders_created_at'), table_name='tenant_orders')
    op.drop_index(op.f('ix_tenant_orders_client_id'), table_name='tenant_orders')
    op.drop_index('ix_tenant_orders_client_created', table_name='tenant_orders')
    op.drop_index('ix_tenant_orders_client_code', table_name='tenant_orders')
    op.drop_table('tenant_orders')
    op.drop_index(op.f('ix_tenant_clients_slug'), table_name='tenant_clients')
    op.drop_index(op.f('ix_tenant_clients_id'), table_name='tenant_clients')
    op.drop_table('tenant_clients')
    # ### end Alembic commands ###
